openapi: 3.0.0
info:
  title: Domostroy API
  version: 1.0.0
servers:
  - url: http://domostroy:8080
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Registration successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
  /auth/confirmRegistration:
    post:
      tags:
        - Auth
      summary: Confirm user registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmRegistrationRequest'
      responses:
        '200':
          description: Registration confirmed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login user and return JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login with JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /offer/place:
    post:
      tags:
        - Core
      summary: Place a new offer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferPlaceRequest'
      responses:
        '200':
          description: Offer placed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
  /offer/{offerId}/apply:
    post:
      tags:
        - Core
      summary: Apply to an offer
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Applied to offer successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
  /offer/{offerId}/reject:
    post:
      tags:
        - Core
      summary: Reject an offer
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Offer rejected successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
  /offer/{offerId}/accept:
    post:
      tags:
        - Core
      summary: Accept an offer
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Offer accepted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
  /offer/{offerId}/ban:
    post:
      tags:
        - Core
      summary: Ban an offer
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Offer banned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
  /find:
    post:
      tags:
        - Core
      summary: Find offers based on search criteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
      responses:
        '200':
          description: Search results returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
        - email
        - password
        - firstName
        - lastName
    ConfirmRegistrationRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        verificationCode:
          type: string
      required:
        - email
        - password
        - verificationCode
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT token
    OfferPlaceRequest:
      type: object
      properties:
        header:
          type: string
        description:
          type: string
        currency:
          type: string
        price:
          type: number
      required:
        - header
        - description
        - currency
        - price
    SearchRequest:
      type: object
      properties:
        query:
          type: string
        filters:
          type: object
      required:
        - query
    SearchResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
